### ISSUE TITLE
On CustomResource replace, eunomia panicks

### ISSUE THREAD

**Issue by sbar95** [KohlsTechnology/eunomia#188]
**What version of eunomia are you using?**

eunomia version: v0.0.4

**Does this issue reproduce with the latest release?**

yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

`minikube version: v1.5.2`

**What did you do?**

I deployed eunomia to minikube with:
`helm template deploy/helm/eunomia-operator/ | kubectl apply -f -`

Then I deployed hello-world app with:
`kubectl create namespace eunomia-hello-world-yaml-demo`
`kubectl apply -f examples/hello-world-yaml/eunomia-runner-sa.yaml -n eunomia-hello-world-yaml-demo`
`kubectl apply -f examples/hello-world-yaml/cr/hello-world-cr1.yaml -n eunomia-hello-world-yaml-demo` (I only changed `eunomia-base:latest` to `eunomia-base:v0.0.3` in [hello-world-cr1.yaml](https://github.com/KohlsTechnology/eunomia/blob/master/examples/hello-world-yaml/cr/hello-world-cr1.yaml#L18))

Lastly I issued:
`kubectl replace -f examples/hello-world-yaml/cr/hello-world-cr1.yaml -n eunomia-hello-world-yaml-demo`

**What did you expect to see?**

Something like:
```
{"level":"info","ts":1575470555.4798508,"logger":"controller_gitopsconfig","msg":"Reconciling GitOpsConfig","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml"}
{"level":"info","ts":1575470555.4798992,"logger":"controller_gitopsconfig","msg":"found instance","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
{"level":"info","ts":1575470555.4799206,"logger":"controller_gitopsconfig","msg":"Instance needs to be initialized","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
{"level":"info","ts":1575470555.4960866,"logger":"controller_gitopsconfig","msg":"Reconciling GitOpsConfig","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml"}
{"level":"info","ts":1575470555.4964414,"logger":"controller_gitopsconfig","msg":"found instance","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
{"level":"info","ts":1575470555.496533,"logger":"controller_gitopsconfig","msg":"Instance is initialized","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
{"level":"info","ts":1575470555.4965618,"logger":"controller_gitopsconfig","msg":"Instance has a change or Webhook trigger, creating job","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
{"level":"info","ts":1575470555.4985273,"logger":"controller_gitopsconfig","msg":"Creating a new Job","job.Namespace":"eunomia-hello-world-yaml-demo","job.Name":"gitopsconfig-hello-world-yaml-8cvlgm"}
```

**What did you see instead?**

```
{"level":"info","ts":1575469578.3754334,"logger":"controller_gitopsconfig","msg":"Reconciling GitOpsConfig","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml"}
{"level":"info","ts":1575469578.3759828,"logger":"controller_gitopsconfig","msg":"found instance","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
{"level":"info","ts":1575469578.3759904,"logger":"controller_gitopsconfig","msg":"Instance needs to be initialized","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
E1204 14:26:18.376065       1 runtime.go:69] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/runtime/runtime.go:76
/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/runtime/runtime.go:65
/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/runtime/runtime.go:51
/home/travis/.gimme/versions/go1.12.13.linux.amd64/src/runtime/panic.go:522
/home/travis/.gimme/versions/go1.12.13.linux.amd64/src/runtime/map_faststr.go:204
/home/travis/gopath/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/controller.go:296
/home/travis/gopath/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/controller.go:142
/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.10/pkg/internal/controller/controller.go:215
/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.10/pkg/internal/controller/controller.go:158
/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:133
/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:134
/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:88
/home/travis/.gimme/versions/go1.12.13.linux.amd64/src/runtime/asm_amd64.s:1337
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map

goroutine 227 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/runtime/runtime.go:58 +0x105
panic(0x129a8e0, 0x15c7dc0)
	/home/travis/.gimme/versions/go1.12.13.linux.amd64/src/runtime/panic.go:522 +0x1b5
github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig.(*Reconciler).initialize(0xc00058c760, 0xc0002ba000, 0x20, 0xc000764200, 0x2, 0x2)
	/home/travis/gopath/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/controller.go:296 +0x1e8
github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig.(*Reconciler).Reconcile(0xc00058c760, 0xc00022f4e0, 0x1d, 0xc00066e5b0, 0x10, 0x211ee40, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/controller.go:142 +0xa3d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0003121e0, 0x0)
	/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.10/pkg/internal/controller/controller.go:215 +0x1cc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
	/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.10/pkg/internal/controller/controller.go:158 +0x36
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000678a30)
	/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:133 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000678a30, 0x3b9aca00, 0x0, 0xc000000001, 0xc000426180)
	/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:134 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000678a30, 0x3b9aca00, 0xc000426180)
	/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.10/pkg/internal/controller/controller.go:157 +0x311
```

**Comment**

It's rather not a normal use case but I think it should be handled.

**Comment by akavel** [comment]
I've seen similar-looking errors sometimes when running our e2e-test.sh script (adding `--verbose` flag to the `operator-sdk test local` line in there may help to show the operator output)
